blank_issues_enabled: false
contact_links:
  - name: Polygon Hermez Docs
    url: https://docs.hermez.io/
    about: Official Polygon Hermez Documentation
  - name: Telegram Group
    url: https://t.me/PolygonHermezChat
    about: Official Polygon Hermez Telegram Group
  - name: Discord Community
    url: https://discord.gg/polygon
    about: Official Polygon Hermez Discord Comunnity
