#!/bin/sh
ENV_FILENAME="/app/.env"

# Create .env file
touch $ENV_FILENAME

# ETHEREUM env vars
echo "VITE_ETHEREUM_RPC_URL=$ETHEREUM_RPC_URL" >> $ENV_FILENAME
echo "VITE_ETHEREUM_EXPLORER_URL=$ETHEREUM_EXPLORER_URL" >> $ENV_FILENAME
echo "VITE_ETHEREUM_BRIDGE_CONTRACT_ADDRESS=$ETHEREUM_BRIDGE_CONTRACT_ADDRESS" >> $ENV_FILENAME
echo "VITE_ETHEREUM_PROOF_OF_EFFICIENCY_CONTRACT_ADDRESS=$ETHEREUM_PROOF_OF_EFFICIENCY_CONTRACT_ADDRESS" >> $ENV_FILENAME

# POLYGON ZK EVM env vars
echo "VITE_POLYGON_ZK_EVM_RPC_URL=$POLYGON_ZK_EVM_RPC_URL" >> $ENV_FILENAME
echo "VITE_POLYGON_ZK_EVM_EXPLORER_URL=$POLYGON_ZK_EVM_EXPLORER_URL" >> $ENV_FILENAME
echo "VITE_POLYGON_ZK_EVM_BRIDGE_CONTRACT_ADDRESS=$POLYGON_ZK_EVM_BRIDGE_CONTRACT_ADDRESS" >> $ENV_FILENAME
echo "VITE_POLYGON_ZK_EVM_NETWORK_ID=$POLYGON_ZK_EVM_NETWORK_ID" >> $ENV_FILENAME

# BRIDGE API env vars
echo "VITE_BRIDGE_API_URL=$BRIDGE_API_URL" >> $ENV_FILENAME

# FIAT EXCHANGE RATES API env vars
echo "VITE_USE_FIAT_EXCHANGE_RATES=$USE_FIAT_EXCHANGE_RATES" >> $ENV_FILENAME

if [ ! -z "$FIAT_EXCHANGE_RATES_API_URL" ];
then
  echo "VITE_FIAT_EXCHANGE_RATES_API_URL=$FIAT_EXCHANGE_RATES_API_URL" >> $ENV_FILENAME
fi

if [ ! -z "$FIAT_EXCHANGE_RATES_API_KEY" ];
then
  echo "VITE_FIAT_EXCHANGE_RATES_API_KEY=$FIAT_EXCHANGE_RATES_API_KEY" >> $ENV_FILENAME
fi

if [ ! -z "$FIAT_EXCHANGE_RATES_ETHEREUM_USDC_ADDRESS" ];
then
  echo "VITE_FIAT_EXCHANGE_RATES_ETHEREUM_USDC_ADDRESS=$FIAT_EXCHANGE_RATES_ETHEREUM_USDC_ADDRESS" >> $ENV_FILENAME
fi

# MISC env vars
echo "VITE_OUTDATED_NETWORK_TITLE=$OUTDATED_NETWORK_TITLE" >> $ENV_FILENAME
echo "VITE_OUTDATED_NETWORK_MESSAGE=$OUTDATED_NETWORK_MESSAGE" >> $ENV_FILENAME
echo "VITE_OUTDATED_NETWORK_URL=$OUTDATED_NETWORK_URL" >> $ENV_FILENAME

# Build app
cd /app && npm run build

# Copy nginx config
cp /app/deployment/nginx.conf /etc/nginx/conf.d/default.conf

# Copy app dist
cp -r /app/dist/. /usr/share/nginx/html

# Delete source code
rm -rf /app

# Run nginx
nginx -g 'daemon off;'
